# permissions for end users to view clusterinformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinformation-viewer-role
rules:
- apiGroups:
  - ferry.daocloud.io
  resources:
  - clusterinformations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ferry.daocloud.io
  resources:
  - clusterinformations/status
  verbs:
  - get
